# Generated by Django 4.2.7 on 2024-03-17 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Administrateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Defi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date_limite", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_equipe", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Jury",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "defi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.defi"
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.equipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prenom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
                ("niveau_etude", models.CharField(max_length=50)),
                ("specialite", models.CharField(max_length=100)),
                (
                    "session_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Soumission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_soumission", models.DateTimeField()),
                ("fichier_soumis", models.CharField(max_length=255)),
                (
                    "defi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.defi"
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.equipe"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=50)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.administrateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "defi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.defi"
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.equipe"
                    ),
                ),
                (
                    "jury",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.jury"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MembreEquipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.equipe"
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="jury",
            name="membre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.utilisateur"
            ),
        ),
        migrations.CreateModel(
            name="GrilleEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("critere", models.CharField(max_length=255)),
                ("coefficient", models.IntegerField()),
                (
                    "defi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.defi"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="equipe",
            name="adjoint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjoint_teams",
                to="api.utilisateur",
            ),
        ),
        migrations.AddField(
            model_name="equipe",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_teams",
                to="api.utilisateur",
            ),
        ),
    ]
