# Generated by Django 4.2.7 on 2024-03-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="niveau_etude",
            field=models.CharField(choices=[("L2", "L2"), ("L3", "L3")], max_length=2),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="specialite",
            field=models.CharField(
                choices=[("DSI", "DSI"), ("RSS", "RSS"), ("CNM", "CNM")], max_length=3
            ),
        ),
    ]
